### PR TITLE
QA8 - 1362 TC-114 automate

### PR DESCRIPTION
**Pull request by ivansh83**
Image upload test. Will try to convert it into a function. There is some hardcoding there, but as of now, I don't know how to go around it. This DOM method only accepts a string.

### CODE REVIEW

**Review by isenkovska — APPROVED** [review]
ok

**Review by isenkovska — CHANGES_REQUESTED** [review]
Please, refactor your code

**Review by EAGauss — APPROVED** [review]
Looks good! I don't know how to improve it so far.

**Review by o-akhadova — APPROVED** [review]
Good job!

**Review by isenkovska — APPROVED** [review]
great

**Review by isenkovska — APPROVED** [review]
awesome)

**Pull request merged**
