### PR TITLE
Added TC-160, TC-161, TC-162, TC-164, TC-173

### PR DESCRIPTION
**Pull request by EAGauss**

### CODE REVIEW

**Review by o-akhadova — APPROVED** [review]
Good job!

**Review by isenkovska — CHANGES_REQUESTED** [review]
TC 160- 164 have the same summary, I think we should specify in summary, what exactly each case does, very confusing to understand what exactly is being tested.

**Comment by EAGauss** [comment]
> TC 160- 164 have the same summary, I think we should specify in summary, what exactly each case does, very confusing to understand what is being tested in every case.

I took summaries from the Google Spreadsheets we reviewed together.
Okay, I will add the corresponding descriptions to not to confuse anyone :)

**Comment by EAGauss** [comment]
> TC 160- 164 have the same summary, I think we should specify in summary, what exactly each case does, very confusing to understand what is being tested in every case.

Done!

**Comment by isenkovska** [comment]
nice one, I don't feel that confused anymore ;))

**Review by isenkovska — APPROVED** [review]

**Pull request merged**
