### PR TITLE
Automated TC-118, 119; added test images for these TC's

### PR DESCRIPTION
**Pull request by ivansh83**

### CODE REVIEW

**Review by EAGauss — CHANGES_REQUESTED** [review]
TC-118 and TC-119 are failing because the images are being uploaded too slowly.
They only completed successfully when I added timeouts before the expects.
`$(sel.imgAlt).waitForDisplayed({ timeout: 20000 });`
I'm not sure if it's a best practice but that's the only idea I came up with to make them work.

**Comment by ivansh83** [comment]
Checked and agree. I think it's the best we can do now with one major exception: we need waitForExist() command to be used, not waitForDisplay() as in this case we want the element to "materialize" in the DOM, not become visible on the screen. That's what I did. Please check my latest commit.

**Review by EAGauss — CHANGES_REQUESTED** [review]
Still getting errors with 10'000 ms timeout.
Could you increase it to 20'000 ms, please?

**Comment by ivansh83** [comment]
Increased to 20 000.

**Review by EAGauss — APPROVED** [review]
Well done!

**Review by o-akhadova — APPROVED** [review]
Looks good! Works with 20 seconds timeout.

**Pull request merged**
