### PR TITLE
Added TC-174 and TC-176

### PR DESCRIPTION
**Pull request by EAGauss**
Updated expects
Removed an empty line in selectors

### CODE REVIEW

**Review by o-akhadova — APPROVED** [review]

**Review by isenkovska — CHANGES_REQUESTED** [review]
summary in tc-1761a - 176g is the same, please specify what each test does.

**Comment by EAGauss** [comment]
> summary in tc-1761a - 176g is the same, please specify what each test does.

Same, I took the summaries from the common Google Spreadsheets but I'll make them more transparent.

**Comment by EAGauss** [comment]
> summary in tc-1761a - 176g is the same, please specify what each test does.

Done!

**Review by isenkovska — APPROVED** [review]
looks way better)

**Pull request merged**
