### PR TITLE
Added from TC-087 to TC-089(placeholder, listOfTheStories)

### PR DESCRIPTION
**Pull request by Slyvochka**

### CODE REVIEW

**Review by irinadash — APPROVED** [review]

**Review by o-akhadova — CHANGES_REQUESTED** [review]
The code works, good job! But can you change the titles in describe according to our spreadsheet, please? They
Screenshot_1
Screenshot_2

 have the same names

**Review by EAGauss — CHANGES_REQUESTED** [review]
Good Job! The code is fine but I also agree with Ksiusha.

**Comment by oksanakirieieva** [comment]
those two passed, just waiting for your changes and ready to approve

**Comment by natdem** [comment]
Please, put a semicolon on line 20. Good job.

**Comment by EAGauss** [comment]
Made minor changes to the branch, the code is fine.

**Pull request merged**
