### PR TITLE
Added in TC-121 Validate with error message and TC-127

### PR DESCRIPTION
**Pull request by irinadash**

### CODE REVIEW

**Review by isenkovska — CHANGES_REQUESTED** [review]
TC-127 looks good, but Looks like image file getting too large, we need either create new file imageNegative and move negative cases into it, or create a method, as we have a lot of redundant code here

**Comment by ivansh83** [comment]
@isenkovska I'm working on the method. Hopefully,it'll be ready by tomorrow morning.

**Comment by isenkovska** [comment]
@ivansh83,  @irinadash just added method for page uploading in methods, I believe you can use it in your tests too, check out my branch

**Review by EAGauss — APPROVED** [review]
I'm Okay with the length of the file.
We'll split it to imageNegative and imagePositive in another branch.

**Review by o-akhadova — APPROVED** [review]

**Pull request merged**
